skip_commits:
  files:
  - .travis.yml
  - '**/*.md'
  - .gitignore
  - LICENSE

# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Visual Studio 2015

configuration:
    # FIXME: uncomment this in case if buildability check for these configurations is required
    # - Debug-SDL1
    # - Debug-SDL2
    - Release-SDL1
    - Release-SDL2

platform:
    - x86
    - x64

skip_tags: true

# clone directory
clone_folder: C:\projects\fheroes2

install:
  - cd C:\projects\fheroes2\script\windows
  - call install_packages.bat

after_build:
  - cmd: cd C:\projects\fheroes2\build\%platform%\%configuration%
  - cmd: 7z a C:\projects\fheroes2\build\%platform%\%configuration%\fheroes2-%platform%-%configuration%.zip fheroes2.exe SDL*.dll
  - cmd: cd C:\projects\fheroes2\script\demo
  - cmd: 7z a C:\projects\fheroes2\build\%platform%\%configuration%\fheroes2-%platform%-%configuration%.zip demo.bat
  - cmd: cd C:\projects\fheroes2
  - cmd: 7z a C:\projects\fheroes2\build\%platform%\%configuration%\fheroes2-%platform%-%configuration%.zip LICENSE

artifacts:
  - path: build\$(platform)\$(configuration)\fheroes2-$(platform)-$(configuration).zip
    name: fheroes2-%platform%-%configuration%

deploy:
  tag: fheroes2-windows-$(platform)-$(configuration)
  release: Windows $(platform) $(configuration) build (latest commit)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: 0KcyoHsROl98QBsNcB+so6hegLvgWZ0R2zYammwgqdDyVXkNDejMjiDpr5sqDnx9
  artifact: /.*\.zip/
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master
